### ISSUE TITLE
Setup regularly scheduled builds

### ISSUE THREAD

**Issue by huddlej** [nextstrain/janus#5]
Ideally, augur builds will be scheduled as a cron job that runs regularly on our local cluster. The jobs should either:

1. Always build every fixed time period OR
2. Check for new fauna data and only build if new data are present

The first option is the easiest because we know roughly how long it will take to complete a full build from scratch and can schedule the cron job to run based on that run time.

The second option is more complicated and will require some checkpointing as part of the following workflow.

1. Every fixed period of time (e.g., 5 minutes):
  * check whether there is an active augur build running
  * ask the fauna database whether there are any new data to download 
2. If there is an active build OR there are no new data available, do nothing.
3. If there are new data available:
  * set the build status to "active"
  * touch the dependency file for fauna download rules in the Snakefile (see below for more detail)
  * queue up a new build on the shared cluster
  * when the build completes, set the build status to "inactive"

Because Snakemake uses a dependency check based on a file's modification timestamp to determine whether to run rules, we could take advantage of this existing mechanism in the cron job. If new data exist on fauna to download, a separate file on the filesystem could be touched. If this file is a dependency for the fauna download rules in the Snakefile, then touching the file will cause all of the Snakefile's rules to be executed.

Running a cron job script that wraps the actual build process and checks a build status file will allow us to easily drop in a different build mechanism in the future if we need to.

**Comment by jstoja** [comment]
Hello @huddlej,

I saw that you're using `AWS Batch` to schedule builds, so this looks to be a solved issue.
Is this still relevant?

Thanks

**Comment by huddlej** [comment]
@jstoja Yes, this is actually a defunct project now and has been superseded by [nextstrain-cli](https://github.com/nextstrain/cli) project

**Comment by jstoja** [comment]
May I suggest to "archive" the repository then?
Currently it is listed in [CodeTriage](https://www.codetriage.com/nextstrain/janus) for people to help with issues.
