### ISSUE TITLE
Enable local use of janus

### ISSUE THREAD

**Issue by trvrb** [nextstrain/janus#6]
This extends from points 1-3 in https://github.com/nextstrain/janus/pull/1#issuecomment-323542211.

There are a number of reasons why running janus locally would be helpful:

1. Easier to develop janus
2. Easier to inspect builds
3. Easier for non-blab folks to run builds
4. We might eventually get a server to run these

I imagine with all the config in Conda now anyway it's better to ditch Docker for a local Mac install (can discuss this however). With dependencies in place, I think the only real thing that needs adjusting is the call to Snakemake:

https://github.com/nextstrain/janus/blob/master/janus#L8

Give `janus` an option like `--cluster` to run `snakemake` with `--cluster-config` or perhaps `--local` to run without `--cluster-config`.

**Comment by huddlej** [comment]
This issue should be resolved by commit 33decbc which adds both a `-l` flag for explicitly requesting local jobs and also checks for the presence of cluster submission executables before trying to submit jobs.
